### ISSUE TITLE
Support logging of preservation actions as part of the object

### ISSUE THREAD

**Issue by zimeon** [OCFL/Use-Cases#22] opened 2018-04-04 21:17 UTC
In my preservation repository I will conduct periodic fixity checks, periodic re-characterization and assessment of at-risk content, and possible migration or derivative generation actions that create new versions. I want to be able to record the results of the checks and actions in a way that lives on as part of the object.

**Comment by ahankinson** [comment] 2018-09-05 11:12
F2F 2018.09.05: Duplicate of #6. Closing.

**Closed by ahankinson** 2018-09-05 11:12 UTC
